name: Continous Deployment Actions Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}  # Public IPv4 DNS
        username: ${{ secrets.USERNAME }}  # ubuntu
        key: ${{ secrets.KEY }}  # SSH private key (sudo cat mykey.pem)
        port: ${{ secrets.PORT }} # 22 default
        script: |
          echo "Deploying to EC2"
          cd /home/ubuntu/fastapi-boilercode
          git pull

    # - name: Run the stack
    #   run: docker-compose up -d

